"""add matrix columns to sessions table

Revision ID: 5eda67ae5d99
Revises: aba7935f9226
Create Date: 2023-12-05 16:27:32.647861
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '5eda67ae5d99'
down_revision = 'aba7935f9226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('matrix_url', sa.String(), nullable=True), schema='events')
    op.add_column('sessions', sa.Column('matrix_room_id', sa.String(), nullable=True), schema='events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'matrix_room_id', schema='events')
    op.drop_column('sessions', 'matrix_url', schema='events')
    # ### end Alembic commands ###
